eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: clientone
  cloud:
    config:
      server:
        git:
          uri: https://github.com/13161270226/config-server.git
          username: 13161270226@163.com
          password: sxl19920226@
server:
  port: 9001
